name: Publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
    workflow_dispatch:

jobs:
    publish:
        # To enable auto publishing to github, update your electron publisher
        # config in package.json > "build" and remove the conditional below

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v3

            - name: Install Node and NPM
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Install Python dependencies
              run: |
                brew install pkg-config libvips python-setuptools

            - name: Install project dependencies
              run: |
                npm install

            - name: Post-install and build
              run: |
                npm run postinstall
                npm run build

            - name: Publish releases
              env:
                  # This is used for uploading release assets to github
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                npm exec electron-builder -- --publish onTagOrDraft --win --mac --linux
