name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  publish_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install project dependencies
        run: |
          npm install
          npm run postinstall

      - name: Package App
        run: |
          npm run package

      - name: Release App
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/build/Tinfy-Setup.exe
            release/build/Tinfy-Setup.exe.blockmap

  publish_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install Tinfy dependencies
        run: |
          npm install

      - name: Package Tinfy
        run: |
          npm run package

      - name: Release Tinfy ${{ github.ref_name }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/build/Tinfy.AppImage
            release/build/latest.yml
            release/build/latest-linux.yml
