name: Publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
    workflow_dispatch:

jobs:
    publish:
        # To enable auto publishing to github, update your electron publisher
        # config in package.json > "build" and remove the conditional below

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-22.04]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v3
            - name: Set env version
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Test
              run: |
                echo $RELEASE_VERSION
                echo ${{ env.RELEASE_VERSION }}

            - name: Install Node and NPM
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Install system dependencies
              run: |
                sudo dpkg --add-architecture i386
                sudo mkdir -pm755 /etc/apt/keyrings
                wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
                sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
                sudo apt update
                sudo apt install -y build-essential libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev libvips-dev python3 python3-pip python3-setuptools python3-dev
                sudo apt install -y --install-recommends winehq-stable

            - name: Install node-gyp dependencies
              run: |
                npm install -g node-gyp node-addon-api

            - name: Install project dependencies
              run: |
                npm install

            - name: Post-install and build
              run: |
                npm run postinstall
                npm run build

            - name: Package app
              run: |
                npm run package

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                draft:
                repository: lMortimerl/tinyfier
                token: ${{ secrets.GITHUB_TOKEN }}
                files: |
                   release/build/Tinfy Setup 0.0.1.exe
                   release/build/Tinfy Setup 0.0.1.exe.blockmap
                   release/build/Tinfy-0.0.1.AppImage
